from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal


TAXONOMY_VERSION = "v1"

SeverityLevel = Literal["INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"]
ConfidenceLevel = Literal["LOW", "MEDIUM", "HIGH"]


@dataclass(frozen=True)
class FindingSpec:
    code: str
    category: str
    default_severity: SeverityLevel
    default_confidence: ConfidenceLevel
    validator_version: str
    explanation: str
    affected_artifact: str
    remediation_class: str
    blocking_eligible_future: bool

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def _spec(
    code: str,
    category: str,
    severity: SeverityLevel,
    confidence: ConfidenceLevel,
    explanation: str,
    affected_artifact: str,
    remediation_class: str,
    blocking_eligible_future: bool,
) -> FindingSpec:
    return FindingSpec(
        code=code,
        category=category,
        default_severity=severity,
        default_confidence=confidence,
        validator_version="shadow_quality_taxonomy_v1",
        explanation=explanation,
        affected_artifact=affected_artifact,
        remediation_class=remediation_class,
        blocking_eligible_future=blocking_eligible_future,
    )


_REGISTRY: dict[str, FindingSpec] = {
    "title_script_semantic_consistency": _spec(
        "title_script_semantic_consistency",
        "semantic_consistency",
        "MEDIUM",
        "MEDIUM",
        "Title and script semantics appear inconsistent.",
        "title_script",
        "revise_title_or_script_focus",
        True,
    ),
    "script_description_consistency": _spec(
        "script_description_consistency",
        "semantic_consistency",
        "MEDIUM",
        "MEDIUM",
        "Description appears inconsistent with script content.",
        "description",
        "align_description_to_script",
        True,
    ),
    "title_thumbnail_consistency": _spec(
        "title_thumbnail_consistency",
        "semantic_consistency",
        "MEDIUM",
        "MEDIUM",
        "Title and thumbnail prompt semantics appear inconsistent.",
        "thumbnail_metadata",
        "align_thumbnail_to_title",
        True,
    ),
    "script_shorts_consistency": _spec(
        "script_shorts_consistency",
        "semantic_consistency",
        "MEDIUM",
        "MEDIUM",
        "Short script appears weakly grounded in main script.",
        "shorts",
        "align_short_to_main_script",
        True,
    ),
    "title_description_consistency": _spec(
        "title_description_consistency",
        "semantic_consistency",
        "MEDIUM",
        "MEDIUM",
        "Title and description appear semantically mismatched.",
        "description",
        "align_title_and_description",
        True,
    ),
    "shorts_title_content_consistency": _spec(
        "shorts_title_content_consistency",
        "semantic_consistency",
        "MEDIUM",
        "MEDIUM",
        "Short title and short content are weakly aligned.",
        "shorts",
        "align_short_title_content",
        True,
    ),
    "duplicate_title_detection": _spec(
        "duplicate_title_detection",
        "duplication",
        "MEDIUM",
        "HIGH",
        "Title appears duplicate or near-duplicate of recent history.",
        "title",
        "increase_title_novelty",
        True,
    ),
    "duplicate_script_detection": _spec(
        "duplicate_script_detection",
        "duplication",
        "HIGH",
        "HIGH",
        "Script appears duplicate or near-duplicate of recent history.",
        "script",
        "rewrite_script_with_new_analysis",
        True,
    ),
    "duplicate_shorts_content": _spec(
        "duplicate_shorts_content",
        "duplication",
        "HIGH",
        "HIGH",
        "Short content appears duplicate or near-duplicate.",
        "shorts",
        "rewrite_short_segment",
        True,
    ),
    "duplicate_thumbnail_text_detection": _spec(
        "duplicate_thumbnail_text_detection",
        "duplication",
        "MEDIUM",
        "HIGH",
        "Thumbnail text appears duplicate of recent history.",
        "thumbnail_metadata",
        "change_thumbnail_text",
        True,
    ),
    "repetitive_opening_detection": _spec(
        "repetitive_opening_detection",
        "repetition",
        "MEDIUM",
        "HIGH",
        "Opening resembles recent scripts too closely.",
        "script",
        "vary_opening_structure",
        True,
    ),
    "repeated_cta_detection": _spec(
        "repeated_cta_detection",
        "repetition",
        "LOW",
        "HIGH",
        "CTA phrase is repeated excessively.",
        "script",
        "reduce_cta_repetition",
        False,
    ),
    "unsupported_financial_claim_detection": _spec(
        "unsupported_financial_claim_detection",
        "financial_claim_risk",
        "HIGH",
        "HIGH",
        "Unsupported certainty-style financial claim detected.",
        "script",
        "replace_with_uncertainty_and_sources",
        True,
    ),
    "unverifiable_insider_information_detection": _spec(
        "unverifiable_insider_information_detection",
        "financial_claim_risk",
        "HIGH",
        "HIGH",
        "Unverifiable insider-information claim detected.",
        "script",
        "remove_insider_claim",
        True,
    ),
    "guaranteed_return_wording_detection": _spec(
        "guaranteed_return_wording_detection",
        "financial_claim_risk",
        "HIGH",
        "HIGH",
        "Guaranteed return wording detected.",
        "script",
        "remove_guarantee_language",
        True,
    ),
    "not_priced_in_claim_detection": _spec(
        "not_priced_in_claim_detection",
        "financial_claim_risk",
        "HIGH",
        "HIGH",
        """"Not priced in" type claim detected.""",
        "script",
        "replace_claim_with_evidence_and_uncertainty",
        True,
    ),
    "secret_institutional_claim_detection": _spec(
        "secret_institutional_claim_detection",
        "financial_claim_risk",
        "HIGH",
        "HIGH",
        "Secret institutional meeting/accumulation claim detected.",
        "script",
        "remove_secret_authority_claim",
        True,
    ),
    "extreme_return_claim_detection": _spec(
        "extreme_return_claim_detection",
        "financial_claim_risk",
        "HIGH",
        "HIGH",
        "Extreme return claim detected.",
        "script",
        "remove_extreme_return_claim",
        True,
    ),
    "urgent_trade_pressure_detection": _spec(
        "urgent_trade_pressure_detection",
        "financial_claim_risk",
        "HIGH",
        "HIGH",
        "Urgent buy/sell pressure language detected.",
        "script",
        "remove_urgent_trade_pressure",
        True,
    ),
    "specific_security_certainty_detection": _spec(
        "specific_security_certainty_detection",
        "financial_claim_risk",
        "HIGH",
        "HIGH",
        "Specific security certainty claim detected.",
        "script",
        "replace_certainty_with_uncertainty",
        True,
    ),
    "fabricated_authority_detection": _spec(
        "fabricated_authority_detection",
        "financial_claim_risk",
        "HIGH",
        "MEDIUM",
        "Unattributed authority/source wording detected.",
        "script",
        "cite_verifiable_sources",
        True,
    ),
    "pump_style_title_detection": _spec(
        "pump_style_title_detection",
        "title_quality",
        "HIGH",
        "HIGH",
        "Pump-style wording detected in title.",
        "title",
        "replace_pump_style_title",
        True,
    ),
    "ticker_company_mismatch_detection": _spec(
        "ticker_company_mismatch_detection",
        "semantic_consistency",
        "HIGH",
        "HIGH",
        "Ticker/company mismatch detected.",
        "title_script",
        "correct_ticker_company_alignment",
        True,
    ),
    "script_thumbnail_prompt_consistency": _spec(
        "script_thumbnail_prompt_consistency",
        "semantic_consistency",
        "MEDIUM",
        "MEDIUM",
        "Thumbnail prompt appears weakly aligned with script.",
        "thumbnail_metadata",
        "align_thumbnail_prompt",
        True,
    ),
    "title_thumbnail_text_consistency": _spec(
        "title_thumbnail_text_consistency",
        "semantic_consistency",
        "MEDIUM",
        "MEDIUM",
        "Thumbnail text appears weakly aligned with title.",
        "thumbnail_metadata",
        "align_thumbnail_text",
        True,
    ),
    "thumbnail_prompt_relevance": _spec(
        "thumbnail_prompt_relevance",
        "thumbnail_metadata_quality",
        "MEDIUM",
        "MEDIUM",
        "Thumbnail prompt appears unrelated to content.",
        "thumbnail_metadata",
        "revise_thumbnail_prompt",
        True,
    ),
    "thumbnail_text_financial_safety": _spec(
        "thumbnail_text_financial_safety",
        "financial_claim_risk",
        "HIGH",
        "HIGH",
        "Financial-risk wording detected in thumbnail text.",
        "thumbnail_metadata",
        "remove_risky_thumbnail_text",
        True,
    ),
    "thumbnail_wealth_imagery_signal": _spec(
        "thumbnail_wealth_imagery_signal",
        "thumbnail_metadata_quality",
        "LOW",
        "MEDIUM",
        "Potentially misleading wealth imagery signal detected.",
        "thumbnail_metadata",
        "review_thumbnail_imagery",
        False,
    ),
    "thumbnail_text_length_convention": _spec(
        "thumbnail_text_length_convention",
        "thumbnail_metadata_quality",
        "LOW",
        "HIGH",
        "Thumbnail text length outside preferred convention.",
        "thumbnail_metadata",
        "adjust_thumbnail_text_length",
        False,
    ),
    "thumbnail_ticker_company_mismatch": _spec(
        "thumbnail_ticker_company_mismatch",
        "semantic_consistency",
        "HIGH",
        "HIGH",
        "Ticker/company mismatch detected in thumbnail context.",
        "thumbnail_metadata",
        "correct_ticker_company_alignment",
        True,
    ),
    "misleading_external_link_context": _spec(
        "misleading_external_link_context",
        "description_quality",
        "MEDIUM",
        "MEDIUM",
        "Description includes potentially misleading external-link framing.",
        "description",
        "remove_misleading_link_language",
        False,
    ),
    "shorts_sentence_completeness": _spec(
        "shorts_sentence_completeness",
        "shorts_structure",
        "MEDIUM",
        "MEDIUM",
        "Short may begin or end mid-sentence.",
        "shorts",
        "improve_sentence_boundaries",
        True,
    ),
    "shorts_abrupt_beginning": _spec(
        "shorts_abrupt_beginning",
        "shorts_structure",
        "MEDIUM",
        "MEDIUM",
        "Short may begin abruptly.",
        "shorts",
        "add_contextual_opening",
        True,
    ),
    "shorts_abrupt_ending": _spec(
        "shorts_abrupt_ending",
        "shorts_structure",
        "MEDIUM",
        "MEDIUM",
        "Short may end abruptly.",
        "shorts",
        "add_complete_ending",
        True,
    ),
    "shorts_missing_context": _spec(
        "shorts_missing_context",
        "shorts_structure",
        "MEDIUM",
        "MEDIUM",
        "Short may miss sufficient context.",
        "shorts",
        "add_context_before_claim",
        True,
    ),
    "shorts_hook_quality": _spec(
        "shorts_hook_quality",
        "shorts_structure",
        "LOW",
        "MEDIUM",
        "Short hook appears weak.",
        "shorts",
        "strengthen_hook",
        False,
    ),
    "shorts_context_without_payoff": _spec(
        "shorts_context_without_payoff",
        "shorts_structure",
        "LOW",
        "MEDIUM",
        "Short has context but weak payoff.",
        "shorts",
        "add_clear_payoff",
        False,
    ),
    "shorts_payoff_without_context": _spec(
        "shorts_payoff_without_context",
        "shorts_structure",
        "LOW",
        "MEDIUM",
        "Short has payoff but weak context.",
        "shorts",
        "add_supporting_context",
        False,
    ),
    "shorts_duration_signal": _spec(
        "shorts_duration_signal",
        "shorts_structure",
        "LOW",
        "HIGH",
        "Short duration signal outside expected range.",
        "shorts",
        "adjust_short_length",
        False,
    ),
    "card_recommendation_not_implemented": _spec(
        "card_recommendation_not_implemented",
        "unsupported_feature",
        "INFO",
        "HIGH",
        "Card recommendation is not implemented in shadow mode.",
        "seo_discovery",
        "keep_advisory_until_supported",
        False,
    ),
    "end_screen_recommendation_not_implemented": _spec(
        "end_screen_recommendation_not_implemented",
        "unsupported_feature",
        "INFO",
        "HIGH",
        "End-screen recommendation is not implemented in shadow mode.",
        "seo_discovery",
        "keep_advisory_until_supported",
        False,
    ),
    "playlist_recommendation_absent": _spec(
        "playlist_recommendation_absent",
        "seo_observability",
        "LOW",
        "HIGH",
        "Playlist recommendation is absent.",
        "seo_discovery",
        "derive_playlist_recommendation",
        False,
    ),
    "validator_exception": _spec(
        "validator_exception",
        "validator_failure",
        "MEDIUM",
        "HIGH",
        "Validator execution raised an exception.",
        "validator",
        "inspect_validator_trace",
        False,
    ),
    "malformed_storage_row": _spec(
        "malformed_storage_row",
        "validator_failure",
        "LOW",
        "HIGH",
        "Malformed row encountered in append-only storage.",
        "storage",
        "skip_and_count_malformed_rows",
        False,
    ),
    "missing_required_input": _spec(
        "missing_required_input",
        "missing_data",
        "MEDIUM",
        "HIGH",
        "Required evaluation input is missing.",
        "context",
        "populate_required_input",
        False,
    ),
    "missing_optional_metadata": _spec(
        "missing_optional_metadata",
        "missing_data",
        "LOW",
        "HIGH",
        "Optional metadata is missing.",
        "metadata",
        "populate_optional_metadata",
        False,
    ),
}


def get_finding_spec(code: str) -> FindingSpec:
    key = str(code or "").strip()
    if key in _REGISTRY:
        return _REGISTRY[key]
    return _spec(
        key or "unknown_finding",
        "validator_failure",
        "LOW",
        "LOW",
        "Unregistered finding code.",
        "validator",
        "register_finding_code",
        False,
    )


def list_finding_specs() -> list[dict[str, object]]:
    return [item.to_dict() for item in sorted(_REGISTRY.values(), key=lambda x: x.code)]
