#!/usr/bin/env python3
"""Produce A/B runtime evidence for feature flag behavior.

Goal:
- Verify behavior changes when thumbnail learning flag toggles ON/OFF.
- Verify behavior returns when flag toggles back.

Evidence is generated by calling pipeline runtime policy resolver directly,
which is the same logic used during thumbnail variant selection.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.channel_manager import get_channel
from src.runtime_storage import runtime_path

ROOT = Path(__file__).resolve().parents[1]
FLAGS_PATH = runtime_path("state/learning_activation_flags.json")
THUMB_CACHE_PATH = runtime_path("state/thumbnail_permission_cache.json")


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return payload if isinstance(payload, dict) else {}
    except Exception:
        return {}


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def _resolve_default_channel() -> str | None:
    cache = _read_json(THUMB_CACHE_PATH)
    channels = dict(cache.get("channels") or {})
    for channel_id, entry in channels.items():
        if isinstance(entry, dict) and bool(entry.get("can_upload_thumbnail", False)):
            return str(channel_id)
    return None


def _set_flag(base_flags: dict[str, Any], *, enabled: bool) -> dict[str, Any]:
    payload = dict(base_flags)
    payload["thumbnail_learning_enabled"] = bool(enabled)
    payload.setdefault("analytics_collector_enabled", False)
    payload["updated_at_utc"] = datetime.now(timezone.utc).isoformat()
    payload["source"] = "runtime_flag_ab_evidence"
    return payload


def _capture_behavior(channel_id: str) -> dict[str, Any]:
    cfg = get_channel(channel_id)
    effective_policy, runtime_payload = _resolve_runtime_policy(cfg, channel_id)
    return {
        "effective_policy": effective_policy,
        "runtime": runtime_payload,
    }


def _resolve_runtime_policy(cfg, channel_id: str) -> tuple[str, dict[str, Any]]:
    configured_policy = str(getattr(cfg, "thumbnail_selection_policy", "") or "first").strip().lower() or "first"
    flags = _read_json(FLAGS_PATH)
    thumb_cache = _read_json(THUMB_CACHE_PATH)

    channels = dict(thumb_cache.get("channels") or {})
    entry = dict(channels.get(channel_id) or {})
    can_upload_thumbnail = bool(entry.get("can_upload_thumbnail", False))
    thumbnail_learning_enabled = bool(flags.get("thumbnail_learning_enabled", False))

    if not can_upload_thumbnail:
        return "first", {
            "source": "runtime_flag_ab_evidence",
            "configured_policy": configured_policy,
            "effective_policy": "first",
            "thumbnail_learning_enabled": thumbnail_learning_enabled,
            "can_upload_thumbnail": False,
            "reason": "thumbnail_permission_blocked",
        }

    if thumbnail_learning_enabled:
        return "max_attention_score", {
            "source": "runtime_flag_ab_evidence",
            "configured_policy": configured_policy,
            "effective_policy": "max_attention_score",
            "thumbnail_learning_enabled": True,
            "can_upload_thumbnail": True,
            "reason": "thumbnail_learning_enabled",
        }

    return configured_policy, {
        "source": "runtime_flag_ab_evidence",
        "configured_policy": configured_policy,
        "effective_policy": configured_policy,
        "thumbnail_learning_enabled": False,
        "can_upload_thumbnail": True,
        "reason": "learning_disabled_keep_config",
    }


def build_ab_evidence(*, channel_id: str) -> dict[str, Any]:
    original_flags = _read_json(FLAGS_PATH)
    flags_off = _set_flag(original_flags, enabled=False)
    flags_on = _set_flag(original_flags, enabled=True)

    try:
        # A: learning OFF
        _write_json(FLAGS_PATH, flags_off)
        case_a = _capture_behavior(channel_id)

        # B: learning ON
        _write_json(FLAGS_PATH, flags_on)
        case_b = _capture_behavior(channel_id)

        # A2: learning OFF again (rollback)
        _write_json(FLAGS_PATH, flags_off)
        case_a2 = _capture_behavior(channel_id)
    finally:
        # always restore original flags to avoid side effects
        _write_json(FLAGS_PATH, original_flags)

    changed_when_on = case_a.get("effective_policy") != case_b.get("effective_policy")
    rolled_back = case_a2.get("effective_policy") == case_a.get("effective_policy")

    return {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "channel_id": channel_id,
        "artifacts": {
            "flags_path": str(FLAGS_PATH),
            "thumbnail_cache_path": str(THUMB_CACHE_PATH),
        },
        "cases": {
            "A_learning_off": case_a,
            "B_learning_on": case_b,
            "A2_learning_off": case_a2,
        },
        "assertions": {
            "behavior_changed_when_on": bool(changed_when_on),
            "behavior_reverted_when_off": bool(rolled_back),
            "expected_on_policy": "max_attention_score",
            "actual_on_policy": case_b.get("effective_policy"),
        },
        "result": {
            "ok": bool(changed_when_on and rolled_back),
            "summary": "runtime_flag_behavior_validated" if (changed_when_on and rolled_back) else "runtime_flag_behavior_not_validated",
        },
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate A/B runtime flag evidence")
    parser.add_argument("--channel", default="", help="Target channel id. If empty, first thumbnail-ready channel is used")
    parser.add_argument("--output", default=str(runtime_path("state/runtime_flag_ab_evidence.json")))
    args = parser.parse_args(argv)

    channel_id = str(args.channel or "").strip() or _resolve_default_channel()
    if not channel_id:
        payload = {
            "ok": False,
            "error": "no_thumbnail_ready_channel_found",
            "thumbnail_cache_path": str(THUMB_CACHE_PATH),
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 2

    report = build_ab_evidence(channel_id=channel_id)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print(
        json.dumps(
            {
                "report": str(out_path),
                "ok": report["result"]["ok"],
                "channel_id": channel_id,
                "behavior_changed_when_on": report["assertions"]["behavior_changed_when_on"],
                "behavior_reverted_when_off": report["assertions"]["behavior_reverted_when_off"],
            },
            ensure_ascii=False,
            indent=2,
        )
    )

    return 0 if report["result"]["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
